### ISSUE TITLE
[token_standard] Need to remove PSP22Mintable

### ISSUE THREAD

**Issue by nad128668** [InkWhale-net/contracts#2]
When token is created, the max cap is minted to the owner. If any tokens got burnt, The owner should never be able to mint again to get back the burnt tokens.

**Comment by hnnam0906** [comment]
@nad128668 : Removed.

https://github.com/InkWhale-net/contracts/blob/e021a68a75e5d7c6526b4be5ae9878a2c50b3735/contracts/token_standard/lib.rs#L83
