### ISSUE TITLE
[token_generator] initialize check cần xem lại đk creation_fee>0

### ISSUE THREAD

**Issue by nad128668** [InkWhale-net/contracts#3]
Hàm initialize dùng đk creation_fee>0 để ko cho owner edit được storage data tuy nhiên là hàm set_creation_fee lại cho phép set creation_fee = 0;

--> solutions:
1. set_creation_fee luôn cho creation_fee > 0; lúc tạo new() cũng cần cho creation_fee > 0;
2. thay vì dùng creation_fee có thể dùng standard_psp22_hash hoặc inw_contract để ktra

**Comment by hnnam0906** [comment]
@nad128668: Change checking condition in initialize func and accept creation fee = 0 (can set create fee to any value >=0 later).

https://github.com/InkWhale-net/contracts/blob/e386fe250e0dabd89306fe2cb1d4c86ab4c14f67/contracts/token_generator/lib.rs#L77
