### ISSUE TITLE
[pool_contract][nft_contract] Check condition before creating

### ISSUE THREAD

**Issue by nad128668** [InkWhale-net/contracts#4]
Các điều kiện sau cần >0:
**NFT contract:**
- min_reward_amount
- max_staking_amount
- multiplier
- duration
- start_time

**Pool contract:**
- max_staking_amount
- min_reward_amount
- multiplier (apy)
- duration
- start_time

**Comment by hnnam0906** [comment]
@nad128668 : Added.

https://github.com/InkWhale-net/contracts/blob/e021a68a75e5d7c6526b4be5ae9878a2c50b3735/contracts/pool_contract/lib.rs#L110

https://github.com/InkWhale-net/contracts/blob/e021a68a75e5d7c6526b4be5ae9878a2c50b3735/contracts/nft_pool_contract/lib.rs#L118
