### ISSUE TITLE
[general_token_sale] set_start_time cần thêm đk check end_time

### ISSUE THREAD

**Issue by nad128668** [InkWhale-net/contracts#6]
Khi tạo contract thì đã set start_time và end_time + start_time < end_time

Tuy nhiên khi gọi hàm set_start_time thì mới chỉ check đk current_time > start_time
chưa check start_time < end_time
sẽ xảy ra trường hợp start_time >= end_time --> lỗi

**Comment by hnnam0906** [comment]
@nad128668  Added 

https://github.com/InkWhale-net/contracts/blob/e021a68a75e5d7c6526b4be5ae9878a2c50b3735/src/impls/generic_token_sale/generic_token_sale.rs#L86
