### ISSUE TITLE
[general_token_sale] hàm set_inw_price đang check đk tgian

### ISSUE THREAD

**Issue by nad128668** [InkWhale-net/contracts#7]
Nếu current_time >= start_time thì ko cho update. Trường hợp muốn thay đổi giá khi đang bán sẽ ko làm được.

Cần bỏ đk tgian này, để owner thích chỉnh lúc nào cũng được.

**Comment by hnnam0906** [comment]
@nad128668: Removed condition

https://github.com/InkWhale-net/contracts/blob/e021a68a75e5d7c6526b4be5ae9878a2c50b3735/src/impls/generic_token_sale/generic_token_sale.rs#L137
