### ISSUE TITLE
hàm initialize cần check xem data đã được tạo chưa

### ISSUE THREAD

**Issue by nad128668** [InkWhale-net/contracts#8]
Nếu đã tạo rồi thì ko cho gọi hàm initialize nữa. Ở tất cả các contract có hàm này

**Comment by hnnam0906** [comment]
@nad128668: Added

1. token_generator
https://github.com/InkWhale-net/contracts/blob/e021a68a75e5d7c6526b4be5ae9878a2c50b3735/contracts/token_generator/lib.rs#L77

2. public_sale
https://github.com/InkWhale-net/contracts/blob/e021a68a75e5d7c6526b4be5ae9878a2c50b3735/contracts/public_sale/lib.rs#L111

3. private_sale
https://github.com/InkWhale-net/contracts/blob/e021a68a75e5d7c6526b4be5ae9878a2c50b3735/contracts/private_sale/lib.rs#L113

4. pool_generator
https://github.com/InkWhale-net/contracts/blob/e021a68a75e5d7c6526b4be5ae9878a2c50b3735/contracts/pool_generator/lib.rs#L75

5. pool_contract
https://github.com/InkWhale-net/contracts/blob/e021a68a75e5d7c6526b4be5ae9878a2c50b3735/contracts/pool_contract/lib.rs#L112
 
6. nft_pool_generator
https://github.com/InkWhale-net/contracts/blob/e021a68a75e5d7c6526b4be5ae9878a2c50b3735/contracts/nft_pool_generator/lib.rs#L76

7. nft_pool_contract
https://github.com/InkWhale-net/contracts/blob/e021a68a75e5d7c6526b4be5ae9878a2c50b3735/contracts/nft_pool_contract/lib.rs#L120

8. launchpad_generator
https://github.com/InkWhale-net/contracts/blob/e021a68a75e5d7c6526b4be5ae9878a2c50b3735/contracts/launchpad_generator/lib.rs#L83

9. launchpad_contract
https://github.com/InkWhale-net/contracts/blob/e021a68a75e5d7c6526b4be5ae9878a2c50b3735/contracts/launchpad_contract/lib.rs#L244
